### ISSUE TITLE
[Bug]: Invalid transition from init to finish_branch

### ISSUE THREAD

**Issue by Ahmad-mtos** [julep-ai/julep#1029]
### 📜 Description

When the main workflow has only one step, it always fails with ``Invalid transition from init to finish_branch``

### 👟 Reproduction steps

```
task_def = yaml.safe_load("""
name: replicate_activity_task_failed

tools:
  - name: get_user_from_ppid
    description: Get a user from the user ppid
    type: system
    system:
      resource: user
      operation: list
                          
main:
  - tool: get_user_from_ppid
    arguments:
      limit: "100"
      sort_by: "'created_at'"
      direction: "'desc'"
""")
```

### 👀 Have you searched previous issues to see if this has been raised before?

- [X] I checked and didn't find similar issue
