### ISSUE TITLE
[Bug]: Deserialization error for integration

### ISSUE THREAD

**Issue by Vedantsahai18** [julep-ai/julep#1120]
### 📜 Description

In the prompt step the python expression sometimes correctly works as it is expected to but sometimes it doesn't and just provides an empty output. Furthermore, commenting out the last steps and then executing the workflow results in correct(at times) output. Its kinda non-deterministic behaviour.
  
Attached below are the steps in the yaml

```yaml
# Define the steps of the workflow
main:

# Step 0: Call the api_tool_call tool with the url input
- tool: api_tool_call
  arguments:
    params:
      q: $ inputs[0].topic
      country: "us"
      language: "en"
      limit: "5"
      # source: "google_news" # A domain of the news source. Example: cnn.com
      # from: "2024-01-01" # A date in the format YYYY-MM-DD
      # to: "2024-01-30" # A date in the format YYYY-MM-DD

# Step 1: Extract the news data from the api_tool_call tool
- evaluate:
    newsdata: $ _['json']['data']

# Step 2: Prompt the agent to find the most overlapping news articles
- prompt: 
  - role: system
    content: >-
      You are a news pattern finder. Your are task is to find some common ground among the news articles.
  - role: user
    content: >-
      Here are the news articles:
      {{$ _['newsdata']}}
      I want you to find some common ground among the news articles based on the news titles and descriptions.
      Return the most overlapping news articles.
      Output needs to be in the following format:
      ```json
        [
          {{
            "title": "News Article Title",
            "url": "News Article URL",
            "description": "News Article Description",
            "thumbnail": "News Article Thumbnail URL",
            
          }}
        ]
      ```
      Provide the output in the json format. And nothing else.
  unwrap: true  

# Step 3: Extract the overlapped news from the prompt step
- evaluate:
    overlapped_news: $ extract_json(_)

# Step 4: Call the spider_crawler tool with the url input
- over: $ _.overlapped_news
  map:
    tool: spider_crawler
    arguments:
      url: $ _.url
      params:
        request: "smart_mode"
        limit: "1"
        return_format: "markdown"
        proxy_enabled: "True"
        filter_output_images: "True"
        filter_output_svg: "True"
        filter_output_main_only: "True"
        readability: "True"
  parallelism: 2
```

Output:
```bash
Transition type:  finish
Transition output:  []
--------------------------------------------------
Transition type:  step
Transition output:  {'overlapped_news': []}
--------------------------------------------------
Transition type:  step
Transition output:  ```json
[]```
--------------------------------------------------
Transition type:  step
Transition output:  {'newsdata': [{'url': 'https://defensescoop.com/2025/01/30/daniel-driscoll-army-secretary-sasc-confirmation-hearing-trump-cots-tech/', 'date': '2025-01-30T16:18:37+00:00', 'title': 'Trump’s nominee for Army secretary calls for buying more commercial off-the-shelf tech', 'source': {'url': 'https://defensescoop.com', 'name': 'DefenseScoop', 'favicon': 'https://staticns.bonai.io/publisher/tFBNU0okSNm8REGnzV0vqPPNKxXRP5vFrGLVnS42sa0'}, 'authors': ['Jon Harper'], 'keywords': [], 'thumbnail': 'https://defensescoop.com/wp-content/uploads/sites/8/2025/01/Daniel-Driscoll.png', 'description': 'Daniel Driscoll, President Donald Trump’s nominee to lead the Army during his second term, told lawmakers that the service should purchase more non-developmental solutions for drones and other technologies to help speed the delivery of new capabilities to soldiers.'}, {'url': 'https://sciencebusiness.net/news/international-news/how-trump-could-impact-eu-us-science-and-technology-relations', 'date': '2025-01-23T08:00:00+00:00', 'title': 'How Trump could impact EU-US science and technology relations', 'source': {'url': 'https://sciencebusiness.net', 'name': 'Science Business', 'favicon': 'https://staticns.bonai.io/publisher/DRCkPD0rbFwuwaTL5ZvrNsdsmBkzU5JAXLEzcHBoMw'}, 'authors': ['David Matthews'], 'keywords': [], 'thumbnail': 'https://sciencebusiness.net/sites/default/files/styles/article/public/2025-01/Untitled%20design(5)_1.png?itok=Q1VApk4L', 'description': 'Donald Trump’s return to the White House has prompted some European research leaders to ask if they should seek out new scientific partners globally, including a rapprochement with China.'}, {'url': 'https://www.theguardian.com/technology/2025/feb/02/elon-musk-doge-access-federal-payment-system', 'date': '2025-02-02T17:13:00+00:00', 'title': 'Elon Musk’s Doge team granted ‘full access’ to federal payment system', 'source': {'url': 'https://www.theguardian.com', 'name': 'The Guardian', 'favicon': 'https://staticns.bonai.io/publisher/8NMzJceUROGieSvOH5XLr5HfyDsH9LjBT2pB2TQI'}, 'authors': ['Ed Pilkington'], 'keywords': [], 'thumbnail': 'https://i.guim.co.uk/img/media/0ceba536be4339c3da9f210babba1315a88921db/0_239_4418_2650/master/4418.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=dab89e4dc80fa337e694040b9e42199d', 'description': 'Trump’s treasury secretary gives the world’s richest person entry to one of the most sensitive US government databases'}, {'url': 'https://www.csis.org/analysis/trumps-moves-modernize-us-technology-policy', 'date': '2025-01-27T21:14:49+00:00', 'title': 'Trump’s Moves to Modernize U.S. Technology Policy', 'source': {'url': 'https://www.csis.org', 'name': 'CSIS | Center for Strategic and International Studies', 'favicon': 'https://staticns.bonai.io/publisher/eLIfE9ZA9S6eOkluDX4EfLvdEdTpfkWykz0BIMTR08'}, 'authors': ['Matt Pearl'], 'keywords': [], 'thumbnail': 'https://csis-website-prod.s3.amazonaws.com/s3fs-public/2025-01/GettyImages-2182611131_cropped.jpg?VersionId=MDMnnxlSJFQNOKjqPVeeJju_7itzLwkr', 'description': 'In this latest commentary, Matt Pearl looks at the new administration’s tech policy priorities and how the disruptor-in-chief will reshape the most disruptive sector.'}, {'url': 'https://www.bbc.com/news/articles/c4gpq01rvd4o', 'date': '2025-01-28T18:04:13+00:00', 'title': 'Nvidia and Microsoft shares steady after DeepSeek AI app shock', 'source': {'url': 'https://www.bbc.com', 'name': 'BBC', 'favicon': 'https://staticns.bonai.io/publisher/bq7G9zXEC8uVJSSwx9TGnJNOONG2Pmgc6cZpBFXU'}, 'authors': ['Peter Hoskins & Charlotte Edwards'], 'keywords': [], 'thumbnail': 'https://ichef.bbci.co.uk/ace/branded_news/1200/cpsprodpb/d54c/live/27f31550-dda1-11ef-926a-cbf3c346618d.jpg', 'description': 'DeepSeek’s claim that its model was made at a fraction of the cost of its rivals has rocked the AI industry.'}]}
--------------------------------------------------
Transition type:  step
Transition output:  {'json': {'data': [{'url': 'https://defensescoo...}],..., 'status_code': 200}
--------------------------------------------------
Transition type:  init
Transition output:  {'topic': 'technology AND donald trump'}
--------------------------------------------------
```

In case all steps go through then I get this error in thh last tool call step
```bash
agents_api.common.exceptions.tools.IntegrationExecutionException: Error in executing spider: Error executing spider method 'crawl_url': Unexpected error occurred while trying to POST to crawl. Status code: 400. Here is the response: {"error":"Deserialization error: readability: invalid type: string \"'True'\", expected a boolean"}
```

Tried with different settings of boolean in yaml ("True", "true", "'true'", "'True'", true, True)

### 👀 Have you searched previous issues to see if this has been raised before?

- [x] I checked and didn't find similar issue
