### ISSUE TITLE
[Bug]: Scalar Values (`int` & `bool`) Not Accepted As Part of Creating/Updating Tasks

### ISSUE THREAD

**Issue by HamadaSalhab** [julep-ai/julep#1137]
## Python SDK Error:

```
UnprocessableEntityError: Error code: 422 - {'errors': ['Input should be a valid string'], 'offending_input': {'tool': 'spider_crawler', 'arguments': {'url': "$ _['url']", 'params': {'proxy_enabled': True, 'chunking_alg': {'type': 'bysentence', 'value': 15}}}}, 'location': ['main', 0, 'ToolCallStep', 'arguments', 'dict[str,union[dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]],list[dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]]],str]]', 'params', 'dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]]', 'chunking_alg', 'dict[str,str]', 'value']}
 ```

## Reproduce

```yaml
- tool: spider_crawler
  arguments:
    url: $ _['url']
    params:
      proxy_enabled: true # Replacing this with "True" passes
      chunking_alg:
        type: bysentence
        value: 15 # Replacing this with "15" or  passes
```

### 👀 Have you searched previous issues to see if this has been raised before?

- [x] I checked and didn't find similar issue
