### ISSUE TITLE
[Feature]: Add secrets store

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#1162]
### 🔖 Feature description

Basically something that can do this:
```yaml
tools:
- name: eat
  type: api_call
  api_call:
    ...
    headers:
      Authorization: $ f"Bearer {secrets.EAT_API_KEY}"

```

guidelines:
- secrets should be encrypted at rest with bcrypt or something (inside the db as well)
- should only be available at "setup time" meaning **not** inside steps

### 🎤 Why is this feature needed ?

cause am secretive

### 👀 Have you searched issues and PRs to see if this feature request has been raised before?

- [x] I checked and didn't find similar issue
