### ISSUE TITLE
[Feature]: File store public signed urls and accessing inside workflows

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#1163]
### 🔖 Feature description

Basically something that can do this:
```yaml
main:
- evaluate:
    url: julep://file.id
```

### 🎤 Why is this feature needed ?

files are awesome, shud be exposed

### 👀 Have you searched issues and PRs to see if this feature request has been raised before?

- [x] I checked and didn't find similar issue
