### ISSUE TITLE
[Feature]: Support python expressions for model settings in `prompt` step

### ISSUE THREAD

**Issue by HamadaSalhab** [julep-ai/julep#1172]
### 🔖 Feature description

Currently the following task fails.

```yaml
main:
- prompt:
    - role: user
      content: Hello
  settings:
    model: $ "gpt-4o-mini"
  unwrap: true
```

Error transition logs:
```
type: error
output: BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': {'error': "/chat/completions: Invalid model name passed in model=$ 'gpt-4o-mini'. Call `/v1/models` to view available models for your key."}, 'type': 'None', 'param': 'None', 'code': '400'}}
```

### 👀 Have you searched issues and PRs to see if this feature request has been raised before?

- [x] I checked and didn't find similar issue
