### ISSUE TITLE
[Bug]: Messages inside `prompt` step accept arbitrary keys

### ISSUE THREAD

**Issue by HamadaSalhab** [julep-ai/julep#1180]
### 📜 Description

For example, the following task gets created without any errors:

```yaml
name: prompt-message-keys-issue

main:
- prompt:
    - role: user
      content: "Hello"
      settings:
        model: "claude-3.5-sonnet"
```

However, it shouldn't be accepted, as it's correct counterpart is the following:

```yaml
name: prompt-message-keys-issue

main:
- prompt:
    - role: user
      content: "Hello"
  settings:
    model: "claude-3.5-sonnet"
```

### 👀 Have you searched previous issues to see if this has been raised before?

- [x] I checked and didn't find similar issue
