### ISSUE TITLE
[Bug]: Unexpected `401` when calling Jina AI with an `api_call` tool

### ISSUE THREAD

**Issue by HamadaSalhab** [julep-ai/julep#1363]
### 📜 Description

Adding an `injectPageScript` body parameter to a JinaAI `api_call` tool gives a `401: Unauthorized`. Noting that the same value for `injectPageScript` works using python `requests` (see reproducing steps).

This was encountered when adding the following:

```yaml
injectPageScript: 
- "setTimeout(() => ``, 500);"
```

inside the `json` argument in the `tool` call step.

### Verify it works with python's `requests`

```py
import requests

url = "https://r.jina.ai/"
headers = {
    "Authorization": "Bearer JINA_AI_TOKEN",
    "Content-Type": "application/json",
    "X-Return-Format": "markdown"
}
data = {
    "url": "https://rwjmsdom.knack.com/clinic-scheduling-dom#dom-schedule-advisor/?view_28_per_page=1000&view_28_page=1",
    "injectPageScript": [
        "setTimeout(() => {\n  // Run after 500ms\n}, 500);"
    ]
}

response = requests.post(url, headers=headers, json=data)
print(response.text)
```

#### Task definition:

```yaml
name: Crawl a website and create a agent document
description: This task crawls a website and creates a agent document
input_schema:
  type: object
  properties:
    url:
      type: string
      description: The URL of the website to crawl
tools:
- name: get_page
  type: api_call
  api_call:
    method: POST
    url: https://r.jina.ai/
    json: {}
    headers:
    accept: application/json
    x-return-format: markdown
    x-with-images-summary: "true"
    x-with-links-summary: "true"
    x-retain-images: none
    x-no-cache: "true"
    Authorization: Bearer JINA_API_KEY

main:
  - tool: get_page
    arguments:
      json:
        url: $ steps[0].input.url
        injectPageScript: 
        - "setTimeout(() => ``, 500);"
```

#### Create and Execute the Task

```py
execution = client.executions.create(
    task_id=task.id,
    input={
        "url": "https://julep.ai",
    }
)
```

#### Last transition `type` and `output`:

```
error
HTTPStatusError: Client error '401 Unauthorized' for url 'https://r.jina.ai/'
```

### 👀 Have you searched previous issues to see if this has been raised before?

- [x] I checked and didn't find similar issue
