### ISSUE TITLE
[Bug]: Fix notebook 10

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#663]
### 📜 Description

the yaml in [cookbook 10](https://github.com/julep-ai/julep/blob/dev/cookbooks/10-Document_Management_and_Search.py) is broken:
```yaml
name: Document Upload and Indexing

input_schema:
  type: object
  properties:
    documents:
      type: array
      items:
        type: object
        properties:
          tile:  
            type: string
          content: 
            type: string
          metadata:
            type: object
                                 
tools:
- name: document_create
  system:
    resource: agent
    subresource: doc
    operation: create                             

main:
- over: inputs[0].documents
  map:
    tool: document_upload
    arguments:
      agent_id: "'{agent.id}'"
      title: _.title
      content: _.content
      metadata: _.metadata

- prompt:
  - role: system
    content: >-
      You have successfully uploaded and indexed {{len(outputs[0])}} documents.
      Provide a summary of the uploaded documents.
```

It should be:

```yaml
name: Document Upload and Indexing
                       
tools:
- name: document_create
  system:
    resource: agent
    subresource: doc
    operation: create                             

main:
- over: inputs[0].documents
  map:
    tool: document_create
    arguments:
      agent_id: "'{agent.id}'"
      data:
        title: _.title
        content: _.content
        metadata: _.metadata
```

### 💻 Operating system

None

### 👀 Have you spent some time to check if this bug has been raised before?

- [ ] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [ ] I agree to follow this project's Code of Conduct
