### ISSUE TITLE
[Feature]: Function definitions as tools should have their parameters object type be type checked (in typespec)

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#762]
### 🔖 Feature description

Function definitions are supposed to be like this:
```yaml
function:
  name: sum
  description: ...
  parameters:
    type: object
    properties:
      a:
         type: number
         default: 0
      b: 
  ... . . ....
  ```
  
But currently we do not do any validation for them in typespec ([code](https://github.com/julep-ai/julep/blob/dev/typespec/tools/models.tsp#L43)). We should use typespec's [jsonschema](https://www.npmjs.com/package/@typespec/json-schema) libs to validate them.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None
