### ISSUE TITLE
[Feature]: Add label lookup for inputs and outputs in tasks

### ISSUE THREAD

**Issue by creatorrr** [julep-ai/julep#791]
### 🔖 Feature description

Right now, inputs and outputs both are a `list[Any]`. We recently updated the typespec for all steps to optionally include a `label?: string`.

Goal is to enable lookup for labels in inputs and outputs so for example:
```yaml
main:
- evaluate:
    a: 1
    b: 2
  label: example
- tool: print
  arguments:
    hello: outputs[“example”].a
    there: outputs[0].b
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None
