### ISSUE TITLE
[Bug]: tool call arguments mappin failure

### ISSUE THREAD

**Issue by Vedantsahai18** [julep-ai/julep#799]
### 📜 Description

```
ERROR:agents_api.web:[{'type': 'missing', 'loc': ('body', 'main', 0, 'EvaluateStep', 'evaluate'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'dict_type', 'loc': ('body', 'main', 0, 'ToolCallStep', 'arguments', 'dict[str,union[dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]],list[dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]]],str]]'), 'msg': 'Input should be a valid dictionary', 'input': ['url']}, {'type': 'dict_type', 'loc': ('body', 'main', 0, 'ToolCallStep', 'arguments', 'list[dict[str,union[dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]],list[dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]]],str]]]', 0), 'msg': 'Input should be a valid dictionary', 'input': 'url'}, {'type': 'literal_error', 'loc': ('body', 'main', 0, 'ToolCallStep', 'arguments', "literal['_']"), 'msg': "Input should be '_'", 'input': ['url'], 'ctx': {'expected': "'_'"}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'PromptStep', 'prompt'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'GetStep', 'get'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'SetStep', 'set'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'LogStep', 'log'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'YieldStep', 'workflow'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'dict_type', 'loc': ('body', 'main', 0, 'YieldStep', 'arguments', 'dict[str,union[list[str],dict[str,str],list[dict[str,str]],str]]'), 'msg': 'Input should be a valid dictionary', 'input': ['url']}, {'type': 'literal_error', 'loc': ('body', 'main', 0, 'YieldStep', 'arguments', "literal['_']"), 'msg': "Input should be '_'", 'input': ['url'], 'ctx': {'expected': "'_'"}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'ReturnStep', 'return'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'SleepStep', 'sleep'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'ErrorWorkflowStep', 'error'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'WaitForInputStep', 'wait_for_input'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'IfElseWorkflowStep', 'if'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'IfElseWorkflowStep', 'then'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'SwitchStep', 'switch'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'ForeachStep', 'foreach'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'ParallelStep', 'parallel'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'Main', 'over'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}, {'type': 'missing', 'loc': ('body', 'main', 0, 'Main', 'map'), 'msg': 'Field required', 'input': {'tool': 'spider_crawler', 'arguments': ['url']}}]
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Vedantsahai18** [comment]
```yaml
chat_task_def = yaml.safe_load(f"""
name: Browserbase Task

tools:
- name: computer
  type: computer_20241022
  computer_20241022:
    display_height_px: 768
    display_width_px: 1024
    display_number: 1

- name: create_session
  type: integration
  integration:
    provider: browserbase
    method: create_session
    setup:
      api_key: "{BROWSERBASE_API_KEY}"
      project_id: "{BROWSERBASE_PROJECT_ID}"
  
- name: get_live_urls
  type: integration
  integration:
    provider: browserbase
    method: get_live_urls
    setup:
      api_key: "{BROWSERBASE_API_KEY}"
      project_id: "{BROWSERBASE_PROJECT_ID}"

- name: get_connect_url
  type: integration
  integration:
    provider: browserbase
    method: get_connect_url
    setup:
      api_key: "{BROWSERBASE_API_KEY}"
      project_id: "{BROWSERBASE_PROJECT_ID}"

- name: perform_action
  type: integration
  integration:
    provider: remote_browser
    method: perform_action
    setup:
      width: "1024"
      height: "768"

- name: spider_crawler
  type: integration
  integration:
    provider: spider
    setup:
      spider_api_key: "sk-8d6285a0-7b9f-493d-bcf4-3e15e68b1304"

main:

- tool: spider_crawler
  arguments:
    url: "'https://julep.ai'"


# - prompt: 
#   - role: user
#     content: >-
#       You have access to a computer. Use it to tell me the current time.
#   disable_cache: true
#   auto_run_tools: true

# - tool: create_session
#   arguments:
#     project_id: "{BROWSERBASE_PROJECT_ID}"

# - evaluate:
#     session_id: "_['id']"

# - tool: get_live_urls
#   arguments:
#     id: "_['session_id']"

# - evaluate:
#     debugger_url: "_['urls']['debuggerUrl']"

# - tool: get_connect_url
#   arguments:
#     id: "outputs[1]['session_id']"

# - evaluate:
#     connect_url: "_['url']"

# - tool: perform_action
#   arguments:
#     connect_url: "_['connect_url']"
#     action: "navigate"
#     text: "'https://julep.ai'"
""")
```
