### ISSUE TITLE
[Bug]: `EvaluateStep` Not Accepting Nested Dictionaries

### ISSUE THREAD

**Issue by HamadaSalhab** [julep-ai/julep#841]
## Reproduce

Sample task (yaml):

```yaml
main:
    - evaluate:
        user_info:
          gender: "'male'"
          age: "25"
```

## Returned Output (transitions.list):

```
Transition #1:
Type: init
Output: {}
---------------------------------------------
Transition #2:
Type: error
Output: Function agents_api.activities.utils.simple_eval_dict() parameter exprs={'user_info': {'age': '25', 'gender': "'male'"}} violates type hint dict[str, str], as dict key str 'user_info' value dict {'age': '25', 'gender': "'male'"} not instance of str.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue
