### ISSUE TITLE
[Bug]: Allow consecutive `finish_branch` transitions

### ISSUE THREAD

**Issue by HamadaSalhab** [julep-ai/julep#956]
### 📜 Description

When executed, the following task gives a `pycozo_async.client.QueryException: Evaluation of expression failed` that's coming from an `Invalid transition` error from `cozo`.

```yaml
custom_workflow:
- evaluate:
    bar: _['foo']

main:
- foreach:
    in: ['Hello', 'World']
    do:
      workflow: custom_workflow
      arguments:
        foo: _
```

Each iteration of the `foreach` step in the `main` workflow creates an `init_branch` transition, which in turn calls the `custom_workflow` to run, which also works in an `init_branch`/`finish_branch` manner. So in the last iteration in the `foreach` step, after calling the `custom_workflow`, which emits a `finish_branch` transition, we should transition to another `finish_branch` to finish the iteration.

### 👀 Have you searched previous issues to see if this has been raised before?

- [X] I checked and didn't find similar issue
